export type CartItem = {
  id: string;
  name: string;
  price: number; // cents or integer currency
  quantity: number;
  image?: string;
};

export type Order = {
  id?: string; // generated by Convex
  customer: {
    name: string;
    email: string;
    phone?: string;
  };
  shipping: {
    address: string;
    city: string;
    state?: string;
    postalCode: string;
    country: string;
  };
  items: CartItem[];
  totals: {
    subtotal: number;
    shipping: number;
    taxes: number;
    grandTotal: number;
  };
  status: string; // e.g., 'pending', 'confirmed'
  createdAt?: string;
};
